Repository Broodco/AllezCine, pull requests merged in 2019-04, with the labels that each got.

#15 lien vers social media
  allezcinefront/src/App.vue
  allezcinefront/src/components/social/cp-Social.vue
Labels: enhancement

#16 drawer bug fixed
  allezcinefront/src/App.vue
  allezcinefront/src/components/navbar/cp-Drawer.vue
Labels: bug

#20 footer
  allezcinefront/src/components/footer/cp-Footer.vue
  allezcinefront/src/components/navbar/cp-Drawer.vue
Labels: enhancement

#24 debug:route + top movies series
  allezcinefront/package.json
  allezcinefront/src/App.vue
  allezcinefront/src/components/main/cp-Gallery.vue
  allezcinefront/src/components/navbar/cp-Navbar.vue
  allezcinefront/src/views/vw-Home.vue
  allezcinefront/src/views/vw-Medias.vue
Labels: bug, enhancement

#28 ajout d'un form de commentaire
  allezcinefront/src/components/main/details/cp-Ajoutcom.vue
  allezcinefront/src/views/vw-Details.vue
Labels: bug

#37 Refactor/axiox file
  allezcineback/Settings/dbconnect.php
  allezcineback/Settings/header.php
  allezcineback/create.php
  allezcineback/likes.php
  allezcineback/read.php
  allezcinefront/src/axios/localAPI.js
  allezcinefront/src/axios/tmdbAPI.js
  allezcinefront/src/components/carousel/cp-Carousel.vue
  allezcinefront/src/components/main/cp-Gallery.vue
  allezcinefront/src/components/main/details/cp-Ajoutcom.vue
  allezcinefront/src/components/main/details/cp-Recap.vue
  allezcinefront/src/components/main/details/cp-ShowComments.vue
  allezcinefront/src/components/navbar/cp-Searchbar.vue
  allezcinefront/src/views/vw-Details.vue
Labels: enhancement
